Decode PublicKeyCredentialOptions Create
tweag/haskell-fido2 pull request #39
Opened 2021-11-04 09:32 UTC by ErinvanderVeen

A small commit to Decode the PublicKeyCredentialOptions of the Create variety.

2021-11-04 15:36 UTC, Infinisil commented
We should insert links and text of the spec where the `MUST ignore unknown` values are done.

2021-11-05 11:25 UTC, Infinisil requested changes

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  decode attachment = Left $ DecodingErrorUnexpectedAttachment attachment
This shouldn't throw an error, see https://www.w3.org/TR/webauthn-2/#dom-authenticatorselectioncriteria-authenticatorattachment

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  decode requirement = Left $ DecodingErrorUnexpectedResidentKeyRequirement requirement
Same here, see https://www.w3.org/TR/webauthn-2/#dom-authenticatorselectioncriteria-residentkey

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +    -- The default is []
Can be removed, same in the `'M.Get` instance

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  decode n = maybe (Left $ DecodingErrorUnexpectedAlgorithmIdentifier n) Right $ PublicKey.toAlg n
The spec doesn't seem to mention what should happen for unknown COSEAlgorithmIdentifier's, so I think erring out is good, but we should add a comment about this, explaining this, linking to the spec

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +      decodeTransport _ = Nothing
All of these special cases should also have a link to the spec and an explanation

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  decode (Just xs) = catMaybes <$> traverse decodeDescriptor xs
Here as well

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  decode _ = Right M.UserVerificationRequirementPreferred
Here as well, link to the spec

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  decode _ = Right M.AttestationConveyancePreferenceNone
Here as well

2021-11-05 11:25 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  decode xs = catMaybes <$> traverse decodeParam xs
Same here

2021-11-08 08:23 UTC, ErinvanderVeen commented
Current failures are due `server/Main.hs` which is currently being reworked. @Infinisil Do you think it is worth fixing the server in this PR when it will be reworked soon anyway?

2021-11-08 12:01 UTC, Infinisil requested changes

2021-11-08 12:01 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript/Decoding.hs
> +  | DecodingErrorUnexpectedResidentKeyRequirement JS.DOMString
Two of these new errors aren't used anymore I believe

2021-11-08 12:08 UTC, Infinisil commented on fido/Crypto/Fido2/Model/JavaScript.hs
> +    -- TODO: Currently a Maybe because webauthn-json doesn't propagate this field to the server.
https://github.com/github/webauthn-json/blob/main/src/basic/schema.ts#L62

2021-11-08 12:28 UTC, ErinvanderVeen commented on fido/Crypto/Fido2/Model/JavaScript.hs
> +    -- TODO: Currently a Maybe because webauthn-json doesn't propagate this field to the server.
I've added them to the tests.

2021-11-08 13:29 UTC, Infinisil approved these changes
Looking good!

2021-11-08 13:29 UTC, merged