Rewrite the README; Rename to WebAuthn; Proper Copyright
tweag/haskell-fido2 pull request #62
Opened 2021-12-08 10:55 UTC by ErinvanderVeen

This MR contains several changes as listed:
- Rewrite the README: completely rewrote the readme to include the binary caches
- Rename the project to WebAuthn, we discussed that Fido2 is not the right name for the library. This does clash with the existing `webauthn` libary, I propose discussing this with the maintainer of the existing library.
- We add a copyright statement, attributing copyright from 2020 to 2021 to @arianvp , the original author of the library, and 2021 and onwards to Tweag I/O

2021-12-08 11:31 UTC, Infinisil commented
I think the readme structure would be good like this:
# Haskell Webauthn Library
## Development environment
### Nix caches
### Nix shell
## Developing the library
## Running the tests
## Running the demo
## License

2021-12-08 14:52 UTC, Infinisil requested changes

2021-12-08 14:52 UTC, Infinisil commented on README.md
> +done using the [instructions][cachix] provided by Cachix.
You can link to https://app.cachix.org/cache/tweag-haskell-fido2 directly

2021-12-08 14:52 UTC, Infinisil commented on README.md
> +Code not formatted using Ormolu is likely to be rejected in CI.
```suggestion
Code not formatted using Ormolu will be rejected in CI.
```

2021-12-08 16:13 UTC, arianvp commented
Hmm it's a shame that we ended up with two implementations of webauthn in parallel.  Is there an intention to merge the https://hackage.haskell.org/package/webauthn project and this one?

2021-12-08 16:14 UTC, arianvp commented
Ah it actually seems to be quite a bit older but just got a lot of recent development. I didn't spot it when I started this library

2021-12-08 16:24 UTC, Infinisil commented
Oh yeah, we were actually in contact with @fumieval from https://github.com/fumieval/webauthn as well, indicating that we'd be working on an updated implementation. So I'm surprised that they starting working on their implementation as well without mentioning it to us. I'd love to unify all of https://github.com/arianvp/haskell-fido2, https://github.com/tweag/haskell-fido2 and https://github.com/fumieval/webauthn into a single library, to be put in https://hackage.haskell.org/package/webauthn.

@fumieval Perhaps we haven't informed you well enough of our efforts, but we've been working on this library here for some months now and we think it's near production-readiness! What are your thoughts?

2021-12-08 19:45 UTC, lykahb commented
A name that contains "WebAuthn" is more accurate because this library does not deal with CTAP, the aspect of FIDO2 about connecting client and authenticator. It may also make it easier to discover the library on Hackage. I don't have an opinion about it being exactly "webauthn" or something like "webauthn-suffix".

Also, it is more straightforward to have the same name for the project and the git repository. Once a new name is confirmed, it's worth renaming a repository too. When I first started using this library, I added a bad dependency haskell-fido2 instead of fido2.

2021-12-09 09:22 UTC, ErinvanderVeen commented
@fumieval We are still working on adding TPM and AndroidSafetyNet attestation. It is nice to hear that we can use the webauthn name for the package, thank you. We will contact you again whenever we reach that point.

2021-12-09 09:38 UTC, fumieval commented
@ErinvanderVeen Great. Once the time is ripe, let me know your Hackage user names and I can add you to the uploaders at any point

2021-12-09 11:20 UTC, Infinisil commented
@fumieval Awesome thanks! Also feel free to let us know if you see anything in our implementation that you'd like to see changed/improved.

2021-12-09 12:55 UTC, merged